
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MvcBigBank.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExceptionLog
{

    public int id { get; set; }

    public string detailDescription { get; set; }

    public System.DateTime eventTime { get; set; }

}

}
